# Test Deploy Diamonds

In [1]:
import pickle
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

loadModel = pickle.load(open('pipe_diamonds.sav', 'rb'))

In [2]:
loadModel.steps

[('OHE', OneHotEncoder(categorical_features=None, categories=None,
         dtype=<class 'numpy.float64'>, handle_unknown='error',
         n_values=None, sparse=True)),
 ('rf', RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
             max_features='auto', max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
             oob_score=False, random_state=42, verbose=0, warm_start=False))]

In [3]:
data = [[0.23, 'Ideal', 'E', 'SI2', 61.5, 55.0, 3.95, 3.98, 2.43]]

In [4]:
df = pd.read_csv('diamonds.csv')
df = df.drop('Unnamed: 0', axis=1)
df.head()

carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [5]:
df[df['carat']==1.04].head()

carat        cut color clarity  depth  table  price     x     y     z
323    1.04    Premium     G      I1   62.2   58.0   2801  6.46  6.41  4.00
857    1.04    Premium     I      I1   61.6   61.0   2870  6.47  6.45  3.98
1422   1.04       Good     I     SI2   59.9   64.0   2970  6.51  6.45  3.88
2521   1.04       Good     H      I1   63.9   58.0   3203  6.35  6.42  4.08
2522   1.04  Very Good     H      I1   61.6   61.0   3203  6.45  6.47  3.98

In [6]:
df.iloc[6290]

carat       1.07
cut        Ideal
color          G
clarity      SI2
depth       61.1
table         57
price       4021
x           6.61
y           6.65
z           4.05
Name: 6290, dtype: object

In [7]:
df = df.drop('price', axis=1)
df.head()

carat      cut color clarity  depth  table     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0  4.34  4.35  2.75

In [8]:
df.iloc[6290]

carat       1.07
cut        Ideal
color          G
clarity      SI2
depth       61.1
table         57
x           6.61
y           6.65
z           4.05
Name: 6290, dtype: object

In [9]:
predictions = loadModel.predict([[1.07, 'Ideal', 'G', 'SI2', 61.1, 57, 6.61, 6.65, 4.05]])
predictions

array([4269.])

In [10]:
df.iloc[1]

carat         0.21
cut        Premium
color            E
clarity        SI1
depth         59.8
table           61
x             3.89
y             3.84
z             2.31
Name: 1, dtype: object

In [11]:
predictions = loadModel.predict([[0.21, 'Premium', 'E', 'SI1', 59.8, 61, 3.89, 3.90, 2.32]])
predictions

array([5289.4])

In [12]:
predictions = loadModel.predict([[0.29, 'Premium', 'E', 'SI1', 59.8, 61, 3.89, 3.90, 2.32]])
predictions

array([551.9])

In [13]:
predictions = loadModel.predict([[0.90, 'Premium', 'E', 'SI1', 59.8, 61, 3.89, 3.90, 2.32]])
predictions

array([3913.2])